application: pixel-dust
version: 2
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: pixel_dust/static/img/favicon.ico
  upload: pixel_dust/static/img/favicon.ico

- url: /robots.txt
  static_files: pixel_dust/static/robots.txt
  upload: pixel_dust/static/robots.txt

- url: /gae_mini_profiler/static
  static_dir: lib/gae_mini_profiler/static

- url: /gae_mini_profiler/.*
  script: lib.gae_mini_profiler.main.application

- url: /static
  static_dir: pixel_dust/static

- url: .*
  script: run.pixel_dust.app
